apiVersion: v1
kind: Namespace
metadata:
  labels:
    nolan: test
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: nginx:1.25.4
          name: web-app
          ports:
            - containerPort: 80
